stages:
  - initial

instal:
  - stage: initial
  - image: node:18-alpine
  - script: 
      - echo "מוריד תלויות"
      - cd server
      - npm ci
      - cd ..
      - cd client
      - npm ci

artifacts:
  paths:
    - server/node_modules/
    - client/node_modules/
