stages:
  - initiall

instal:
  stage: initiall
  image: node:18-alpine
  script:
    - echo "Installing dependencies"
    - cd server
    - npm ci
    - cd ..
    - cd client
    - npm ci

artifacts:
  paths:
    - server/node_modules/
    - client/node_modules/
test:
  stage: test
  image: node:18-alpine
  script:
    - echo "Running tests"
    - cd server
    - npm run test
    dependencies:
      - install

